### ISSUE TITLE
Where can I find the models from AGORA2?

### ISSUE THREAD

**Issue by rcolpo** [VirtualMetabolicHuman/AGORA2#1]
I can find the model for AGORA 1.03 [here](https://github.com/almut-heinken/AGORA/tree/master/CurrentVersion), but where can I find the models for AGORA2?

**Comment by ithiele** [comment]
Hi 
The AGORA2 reconstructions can be found here: 
https://vmh.life/files/reconstructions/AGORA2/version2.01/

Please cite when using in part or in full: https://www.nature.com/articles/s41587-022-01628-0
